name: Release

on:
  push:
    branches:
      - master

jobs:
  release-void:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@1.92
        with:
          components: clippy,rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo test
      - run: cargo build --example void --release
